export interface AddressOption {
    value: string;
    label: string;
    children?: AddressOption[];
}

export const beijingAddressData: AddressOption[] = [
    {
        "value": "东城区",
        "label": "东城区",
        "children": [
            { "value": "和平里街道", "label": "和平里街道" },
            { "value": "安定门街道", "label": "安定门街道" },
            { "value": "交道口街道", "label": "交道口街道" },
            { "value": "东华门街道", "label": "东华门街道" },
            { "value": "景山街道", "label": "景山街道" },
            { "value": "北新桥街道", "label": "北新桥街道" },
            { "value": "东四街道", "label": "东四街道" },
            { "value": "朝阳门街道", "label": "朝阳门街道" },
            { "value": "建国门街道", "label": "建国门街道" },
            { "value": "东直门街道", "label": "东直门街道" },
            { "value": "体育馆路街道", "label": "体育馆路街道" },
            { "value": "天坛街道", "label": "天坛街道" },
            { "value": "永定门外街道", "label": "永定门外街道" },
            { "value": "前门街道", "label": "前门街道" },
            { "value": "崇文门外街道", "label": "崇文门外街道" },
            { "value": "东花市街道", "label": "东花市街道" },
            { "value": "龙潭街道", "label": "龙潭街道" }
        ]
    },
    {
        "value": "西城区",
        "label": "西城区",
        "children": [
            { "value": "西长安街街道", "label": "西长安街街道" },
            { "value": "新街口街道", "label": "新街口街道" },
            { "value": "金融街街道", "label": "金融街街道" },
            { "value": "德胜街道", "label": "德胜街道" },
            { "value": "月坛街道", "label": "月坛街道" },
            { "value": "展览路街道", "label": "展览路街道" },
            { "value": "什刹海街道", "label": "什刹海街道" },
            { "value": "大栅栏街道", "label": "大栅栏街道" },
            { "value": "天桥街道", "label": "天桥街道" },
            { "value": "椿树街道", "label": "椿树街道" },
            { "value": "陶然亭街道", "label": "陶然亭街道" },
            { "value": "广安门内街道", "label": "广安门内街道" },
            { "value": "牛街街道", "label": "牛街街道" },
            { "value": "白纸坊街道", "label": "白纸坊街道" },
            { "value": "广安门外街道", "label": "广安门外街道" }
        ]
    },
    {
        "value": "朝阳区",
        "label": "朝阳区",
        "children": [
            { "value": "朝外街道", "label": "朝外街道" },
            { "value": "建外街道", "label": "建外街道" },
            { "value": "呼家楼街道", "label": "呼家楼街道" },
            { "value": "八里庄街道", "label": "八里庄街道" },
            { "value": "三里屯街道", "label": "三里屯街道" },
            { "value": "团结湖街道", "label": "团结湖街道" },
            { "value": "双井街道", "label": "双井街道" },
            { "value": "劲松街道", "label": "劲松街道" },
            { "value": "潘家园街道", "label": "潘家园街道" },
            { "value": "垡头街道", "label": "垡头街道" },
            { "value": "左家庄街道", "label": "左家庄街道" },
            { "value": "小关街道", "label": "小关街道" },
            { "value": "和平街街道", "label": "和平街街道" },
            { "value": "安贞街道", "label": "安贞街道" },
            { "value": "亚运村街道", "label": "亚运村街道" },
            { "value": "香河园街道", "label": "香河园街道" },
            { "value": "奥运村街道", "label": "奥运村街道" },
            { "value": "望京街道", "label": "望京街道" },
            { "value": "东湖街道", "label": "东湖街道" },
            { "value": "大屯街道", "label": "大屯街道" },
            { "value": "麦子店街道", "label": "麦子店街道" },
            { "value": "首都机场街道", "label": "首都机场街道" },
            { "value": "六里屯街道", "label": "六里屯街道" },
            { "value": "酒仙桥街道", "label": "酒仙桥街道" },
            { "value": "南磨房地区", "label": "南磨房地区" },
            { "value": "高碑店地区", "label": "高碑店地区" },
            { "value": "将台地区", "label": "将台地区" },
            { "value": "太阳宫地区", "label": "太阳宫地区" },
            { "value": "十八里店地区", "label": "十八里店地区" },
            { "value": "平房地区", "label": "平房地区" },
            { "value": "东风地区", "label": "东风地区" },
            { "value": "来广营地区", "label": "来广营地区" },
            { "value": "常营地区", "label": "常营地区" },
            { "value": "三间房地区", "label": "三间房地区" },
            { "value": "管庄地区", "label": "管庄地区" },
            { "value": "金盏地区", "label": "金盏地区" },
            { "value": "孙河地区", "label": "孙河地区" },
            { "value": "崔各庄地区", "label": "崔各庄地区" },
            { "value": "豆各庄地区", "label": "豆各庄地区" },
            { "value": "黑庄户地区", "label": "黑庄户地区" },
            { "value": "小红门地区", "label": "小红门地区" },
            { "value": "王四营地区", "label": "王四营地区" },
            { "value": "东坝地区", "label": "东坝地区" }
        ]
    },
    {
        "value": "海淀区",
        "label": "海淀区",
        "children": [
            { "value": "万寿路街道", "label": "万寿路街道" },
            { "value": "永定路街道", "label": "永定路街道" },
            { "value": "羊坊店街道", "label": "羊坊店街道" },
            { "value": "甘家口街道", "label": "甘家口街道" },
            { "value": "八里庄街道", "label": "八里庄街道" },
            { "value": "紫竹院街道", "label": "紫竹院街道" },
            { "value": "北下关街道", "label": "北下关街道" },
            { "value": "北太平庄街道", "label": "北太平庄街道" },
            { "value": "学院路街道", "label": "学院路街道" },
            { "value": "中关村街道", "label": "中关村街道" },
            { "value": "海淀街道", "label": "海淀街道" },
            { "value": "青龙桥街道", "label": "青龙桥街道" },
            { "value": "清河街道", "label": "清河街道" },
            { "value": "花园路街道", "label": "花园路街道" },
            { "value": "西三旗街道", "label": "西三旗街道" },
            { "value": "马连洼街道", "label": "马连洼街道" },
            { "value": "香山街道", "label": "香山街道" },
            { "value": "上地街道", "label": "上地街道" },
            { "value": "燕园街道", "label": "燕园街道" },
            { "value": "清华园街道", "label": "清华园街道" },
            { "value": "曙光街道", "label": "曙光街道" },
            { "value": "田村路街道", "label": "田村路街道" },
            { "value": "四季青镇", "label": "四季青镇" },
            { "value": "东升镇", "label": "东升镇" },
            { "value": "海淀镇", "label": "海淀镇" },
            { "value": "西北旺镇", "label": "西北旺镇" },
            { "value": "温泉镇", "label": "温泉镇" },
            { "value": "苏家坨镇", "label": "苏家坨镇" },
            { "value": "上庄镇", "label": "上庄镇" }
        ]
    },
    {
        "value": "丰台区",
        "label": "丰台区",
        "children": [
            { "value": "右安门街道", "label": "右安门街道" },
            { "value": "太平桥街道", "label": "太平桥街道" },
            { "value": "西罗园街道", "label": "西罗园街道" },
            { "value": "大红门街道", "label": "大红门街道" },
            { "value": "南苑街道", "label": "南苑街道" },
            { "value": "东高地街道", "label": "东高地街道" },
            { "value": "东铁匠营街道", "label": "东铁匠营街道" },
            { "value": "六里桥街道", "label": "六里桥街道" },
            { "value": "丰台街道", "label": "丰台街道" },
            { "value": "新村街道", "label": "新村街道" },
            { "value": "长辛店街道", "label": "长辛店街道" },
            { "value": "云岗街道", "label": "云岗街道" },
            { "value": "马家堡街道", "label": "马家堡街道" },
            { "value": "和义街道", "label": "和义街道" },
            { "value": "宛平街道", "label": "宛平街道" },
            { "value": "卢沟桥街道", "label": "卢沟桥街道" },
            { "value": "花乡街道", "label": "花乡街道" },
            { "value": "成寿寺街道", "label": "成寿寺街道" },
            { "value": "石榴庄街道", "label": "石榴庄街道" },
            { "value": "玉泉营街道", "label": "玉泉营街道" },
            { "value": "看丹街道", "label": "看丹街道" },
            { "value": "方庄地区", "label": "方庄地区" },
            { "value": "南苑地区（南苑乡）", "label": "南苑地区（南苑乡）" },
            { "value": "卢沟桥地区（卢沟桥乡）", "label": "卢沟桥地区（卢沟桥乡）" },
            { "value": "花乡地区（花乡）", "label": "花乡地区（花乡）" },
            { "value": "长辛店镇", "label": "长辛店镇" },
            { "value": "王佐镇", "label": "王佐镇" }
        ]
    },
    {
        "value": "石景山区",
        "label": "石景山区",
        "children": [
            { "value": "八宝山街道", "label": "八宝山街道" },
            { "value": "老山街道", "label": "老山街道" },
            { "value": "八角街道", "label": "八角街道" },
            { "value": "古城街道", "label": "古城街道" },
            { "value": "苹果园街道", "label": "苹果园街道" },
            { "value": "金顶街街道", "label": "金顶街街道" },
            { "value": "广宁街道", "label": "广宁街道" },
            { "value": "五里坨街道", "label": "五里坨街道" },
            { "value": "鲁谷街道", "label": "鲁谷街道" }
        ]
    },
    {
        "value": "门头沟区",
        "label": "门头沟区",
        "children": [
            { "value": "大峪街道", "label": "大峪街道" },
            { "value": "城子街道", "label": "城子街道" },
            { "value": "东辛房街道", "label": "东辛房街道" },
            { "value": "大台街道", "label": "大台街道" },
            { "value": "王平地区", "label": "王平地区" },
            { "value": "永定地区", "label": "永定地区" },
            { "value": "龙泉地区", "label": "龙泉地区" },
            { "value": "潭柘寺镇", "label": "潭柘寺镇" },
            { "value": "军庄镇", "label": "军庄镇" },
            { "value": "妙峰山镇", "label": "妙峰山镇" },
            { "value": "雁翅镇", "label": "雁翅镇" },
            { "value": "斋堂镇", "label": "斋堂镇" },
            { "value": "清水镇", "label": "清水镇" }
        ]
    },
    {
        "value": "房山区",
        "label": "房山区",
        "children": [
            { "value": "城关街道", "label": "城关街道" },
            { "value": "新镇街道", "label": "新镇街道" },
            { "value": "向阳街道", "label": "向阳街道" },
            { "value": "东风街道", "label": "东风街道" },
            { "value": "迎风街道", "label": "迎风街道" },
            { "value": "星城街道", "label": "星城街道" },
            { "value": "拱辰街道", "label": "拱辰街道" },
            { "value": "西潞街道", "label": "西潞街道" },
            { "value": "良乡地区", "label": "良乡地区" },
            { "value": "周口店地区", "label": "周口店地区" },
            { "value": "琉璃河地区", "label": "琉璃河地区" },
            { "value": "阎村镇", "label": "阎村镇" },
            { "value": "窦店镇", "label": "窦店镇" },
            { "value": "石楼镇", "label": "石楼镇" },
            { "value": "长阳镇", "label": "长阳镇" },
            { "value": "河北镇", "label": "河北镇" },
            { "value": "长沟镇", "label": "长沟镇" },
            { "value": "大石窝镇", "label": "大石窝镇" },
            { "value": "张坊镇", "label": "张坊镇" },
            { "value": "十渡镇", "label": "十渡镇" },
            { "value": "青龙湖镇", "label": "青龙湖镇" },
            { "value": "韩村河镇", "label": "韩村河镇" },
            { "value": "霞云岭乡", "label": "霞云岭乡" },
            { "value": "南窖乡", "label": "南窖乡" },
            { "value": "佛子庄乡", "label": "佛子庄乡" },
            { "value": "大安山乡", "label": "大安山乡" },
            { "value": "史家营乡", "label": "史家营乡" },
            { "value": "蒲洼乡", "label": "蒲洼乡" }
        ]
    },
    {
        "value": "通州区",
        "label": "通州区",
        "children": [
            { "value": "中仓街道", "label": "中仓街道" },
            { "value": "新华街道", "label": "新华街道" },
            { "value": "北苑街道", "label": "北苑街道" },
            { "value": "玉桥街道", "label": "玉桥街道" },
            { "value": "潞源街道", "label": "潞源街道" },
            { "value": "通运街道", "label": "通运街道" },
            { "value": "文景街道", "label": "文景街道" },
            { "value": "九棵树街道", "label": "九棵树街道" },
            { "value": "临河里街道", "label": "临河里街道" },
            { "value": "杨庄街道", "label": "杨庄街道" },
            { "value": "潞邑街道", "label": "潞邑街道" },
            { "value": "永顺镇", "label": "永顺镇" },
            { "value": "梨园镇", "label": "梨园镇" },
            { "value": "宋庄镇", "label": "宋庄镇" },
            { "value": "张家湾镇", "label": "张家湾镇" },
            { "value": "漷县镇", "label": "漷县镇" },
            { "value": "马驹桥镇", "label": "马驹桥镇" },
            { "value": "西集镇", "label": "西集镇" },
            { "value": "台湖镇", "label": "台湖镇" },
            { "value": "永乐店镇", "label": "永乐店镇" },
            { "value": "潞城镇", "label": "潞城镇" },
            { "value": "于家务回族乡", "label": "于家务回族乡" }
        ]
    },
    {
        "value": "顺义区",
        "label": "顺义区",
        "children": [
            { "value": "胜利街道", "label": "胜利街道" },
            { "value": "光明街道", "label": "光明街道" },
            { "value": "石园街道", "label": "石园街道" },
            { "value": "双丰街道", "label": "双丰街道" },
            { "value": "旺泉街道", "label": "旺泉街道" },
            { "value": "空港街道", "label": "空港街道" },
            { "value": "仁和地区", "label": "仁和地区" },
            { "value": "马坡地区", "label": "马坡地区" },
            { "value": "后沙峪地区", "label": "后沙峪地区" },
            { "value": "天竺地区", "label": "天竺地区" },
            { "value": "杨镇地区", "label": "杨镇地区" },
            { "value": "牛栏山地区", "label": "牛栏山地区" },
            { "value": "南法信地区", "label": "南法信地区" },
            { "value": "高丽营镇", "label": "高丽营镇" },
            { "value": "李桥镇", "label": "李桥镇" },
            { "value": "李遂镇", "label": "李遂镇" },
            { "value": "南彩镇", "label": "南彩镇" },
            { "value": "北务镇", "label": "北务镇" },
            { "value": "大孙各庄镇", "label": "大孙各庄镇" },
            { "value": "张镇", "label": "张镇" },
            { "value": "龙湾屯镇", "label": "龙湾屯镇" },
            { "value": "木林镇", "label": "木林镇" },
            { "value": "北小营镇", "label": "北小营镇" },
            { "value": "赵全营镇", "label": "赵全营镇" },
            { "value": "北石槽镇", "label": "北石槽镇" }
        ]
    },
    {
        "value": "昌平区",
        "label": "昌平区",
        "children": [
            { "value": "城北街道", "label": "城北街道" },
            { "value": "城南街道", "label": "城南街道" },
            { "value": "天通苑北街道", "label": "天通苑北街道" },
            { "value": "天通苑南街道", "label": "天通苑南街道" },
            { "value": "霍营街道", "label": "霍营街道" },
            { "value": "回龙观街道", "label": "回龙观街道" },
            { "value": "龙泽园街道", "label": "龙泽园街道" },
            { "value": "史各庄街道", "label": "史各庄街道" },
            { "value": "阳坊镇", "label": "阳坊镇" },
            { "value": "小汤山镇", "label": "小汤山镇" },
            { "value": "南口地区", "label": "南口地区" },
            { "value": "马池口地区", "label": "马池口地区" },
            { "value": "沙河地区", "label": "沙河地区" },
            { "value": "东小口地区", "label": "东小口地区" },
            { "value": "北七家镇", "label": "北七家镇" },
            { "value": "兴寿镇", "label": "兴寿镇" },
            { "value": "流村镇", "label": "流村镇" },
            { "value": "崔村镇", "label": "崔村镇" },
            { "value": "南邵镇", "label": "南邵镇" },
            { "value": "十三陵镇", "label": "十三陵镇" },
            { "value": "百善镇", "label": "百善镇" },
            { "value": "延寿镇", "label": "延寿镇" }
        ]
    },
    {
        "value": "大兴区",
        "label": "大兴区",
        "children": [
            { "value": "兴丰街道", "label": "兴丰街道" },
            { "value": "林校路街道", "label": "林校路街道" },
            { "value": "清源街道", "label": "清源街道" },
            { "value": "观音寺街道", "label": "观音寺街道" },
            { "value": "天宫院街道", "label": "天宫院街道" },
            { "value": "高米店街道", "label": "高米店街道" },
            { "value": "荣华街道", "label": "荣华街道" },
            { "value": "博兴街道", "label": "博兴街道" },
            { "value": "亦庄地区（亦庄镇）", "label": "亦庄地区（亦庄镇）" },
            { "value": "黄村地区（黄村镇）", "label": "黄村地区（黄村镇）" },
            { "value": "旧宫地区（旧宫镇）", "label": "旧宫地区（旧宫镇）" },
            { "value": "西红门地区（西红门镇）", "label": "西红门地区（西红门镇）" },
            { "value": "瀛海地区（瀛海镇）", "label": "瀛海地区（瀛海镇）" },
            { "value": "青云店镇", "label": "青云店镇" },
            { "value": "采育镇", "label": "采育镇" },
            { "value": "安定镇", "label": "安定镇" },
            { "value": "礼贤镇", "label": "礼贤镇" },
            { "value": "榆垡镇", "label": "榆垡镇" },
            { "value": "庞各庄镇", "label": "庞各庄镇" },
            { "value": "北臧村镇", "label": "北臧村镇" },
            { "value": "魏善庄镇", "label": "魏善庄镇" },
            { "value": "长子营镇", "label": "长子营镇" },
            { "value": "北京经济技术开发区（部分）", "label": "北京经济技术开发区（部分）" }
        ]
    },
    {
        "value": "怀柔区",
        "label": "怀柔区",
        "children": [
            { "value": "泉河街道", "label": "泉河街道" },
            { "value": "龙山街道", "label": "龙山街道" },
            { "value": "怀柔地区（怀柔镇）", "label": "怀柔地区（怀柔镇）" },
            { "value": "雁栖地区（雁栖镇）", "label": "雁栖地区（雁栖镇）" },
            { "value": "庙城地区（庙城镇）", "label": "庙城地区（庙城镇）" },
            { "value": "北房镇", "label": "北房镇" },
            { "value": "杨宋镇", "label": "杨宋镇" },
            { "value": "桥梓镇", "label": "桥梓镇" },
            { "value": "怀北镇", "label": "怀北镇" },
            { "value": "汤河口镇", "label": "汤河口镇" },
            { "value": "渤海镇", "label": "渤海镇" },
            { "value": "九渡河镇", "label": "九渡河镇" },
            { "value": "琉璃庙镇", "label": "琉璃庙镇" },
            { "value": "宝山镇", "label": "宝山镇" },
            { "value": "长哨营满族乡", "label": "长哨营满族乡" },
            { "value": "喇叭沟门满族乡", "label": "喇叭沟门满族乡" }
        ]
    },
    {
        "value": "平谷区",
        "label": "平谷区",
        "children": [
            { "value": "滨河街道", "label": "滨河街道" },
            { "value": "兴谷街道", "label": "兴谷街道" },
            { "value": "渔阳地区（平谷镇）", "label": "渔阳地区（平谷镇）" },
            { "value": "峪口地区（峪口镇）", "label": "峪口地区（峪口镇）" },
            { "value": "马坊地区（马坊镇）", "label": "马坊地区（马坊镇）" },
            { "value": "金海湖地区（金海湖镇）", "label": "金海湖地区（金海湖镇）" },
            { "value": "东高村镇", "label": "东高村镇" },
            { "value": "山东庄镇", "label": "山东庄镇" },
            { "value": "南独乐河镇", "label": "南独乐河镇" },
            { "value": "大华山镇", "label": "大华山镇" },
            { "value": "夏各庄镇", "label": "夏各庄镇" },
            { "value": "马昌营镇", "label": "马昌营镇" },
            { "value": "王辛庄镇", "label": "王辛庄镇" },
            { "value": "大兴庄镇", "label": "大兴庄镇" },
            { "value": "刘家店镇", "label": "刘家店镇" },
            { "value": "镇罗营镇", "label": "镇罗营镇" },
            { "value": "黄松峪乡", "label": "黄松峪乡" },
            { "value": "熊儿寨乡", "label": "熊儿寨乡" }
        ]
    },
    {
        "value": "密云区",
        "label": "密云区",
        "children": [
            { "value": "鼓楼街道", "label": "鼓楼街道" },
            { "value": "果园街道", "label": "果园街道" },
            { "value": "檀营地区（檀营满族蒙古族乡）", "label": "檀营地区（檀营满族蒙古族乡）" },
            { "value": "密云镇", "label": "密云镇" },
            { "value": "溪翁庄镇", "label": "溪翁庄镇" },
            { "value": "西田各庄镇", "label": "西田各庄镇" },
            { "value": "十里堡镇", "label": "十里堡镇" },
            { "value": "河南寨镇", "label": "河南寨镇" },
            { "value": "巨各庄镇", "label": "巨各庄镇" },
            { "value": "穆家峪镇", "label": "穆家峪镇" },
            { "value": "太师屯镇", "label": "太师屯镇" },
            { "value": "高岭镇", "label": "高岭镇" },
            { "value": "不老屯镇", "label": "不老屯镇" },
            { "value": "冯家峪镇", "label": "冯家峪镇" },
            { "value": "古北口镇", "label": "古北口镇" },
            { "value": "大城子镇", "label": "大城子镇" },
            { "value": "东邵渠镇", "label": "东邵渠镇" },
            { "value": "北庄镇", "label": "北庄镇" },
            { "value": "新城子镇", "label": "新城子镇" },
            { "value": "石城镇", "label": "石城镇" }
        ]
    },
    {
        "value": "延庆区",
        "label": "延庆区",
        "children": [
            { "value": "百泉街道", "label": "百泉街道" },
            { "value": "香水园街道", "label": "香水园街道" },
            { "value": "儒林街道", "label": "儒林街道" },
            { "value": "延庆镇", "label": "延庆镇" },
            { "value": "康庄镇", "label": "康庄镇" },
            { "value": "八达岭镇", "label": "八达岭镇" },
            { "value": "永宁镇", "label": "永宁镇" },
            { "value": "旧县镇", "label": "旧县镇" },
            { "value": "张山营镇", "label": "张山营镇" },
            { "value": "四海镇", "label": "四海镇" },
            { "value": "千家店镇", "label": "千家店镇" },
            { "value": "沈家营镇", "label": "沈家营镇" },
            { "value": "大榆树镇", "label": "大榆树镇" },
            { "value": "井庄镇", "label": "井庄镇" },
            { "value": "大庄科乡", "label": "大庄科乡" },
            { "value": "刘斌堡乡", "label": "刘斌堡乡" },
            { "value": "香营乡", "label": "香营乡" },
            { "value": "珍珠泉乡", "label": "珍珠泉乡" }
        ]
    }
]